Repository diasurgical/devilution, pull requests merged in 2018-10, with the labels that each got.

#353 Sound.cpp
  Source/effects.cpp
  Source/sound.cpp
  Source/sound.h
  Source/wave.cpp
  Source/wave.h
  structs.h
Labels: Binary exact

#368 Cleanup "DRLG_L5"
  Source/drlg_l1.cpp
Labels: Minimal differences

#372 Cleanup L5roomGen
  Source/drlg_l1.cpp
  Source/drlg_l1.h
Labels: Binary exact

#371 PlaySFX_priv, stream_play
  Source/effects.cpp
  Source/effects.h
  Source/gamemenu.cpp
  Source/player.cpp
  Source/sound.cpp
  defs.h
  enums.h
Labels: Binary exact

#378 movie.cpp
  3rdParty/Storm/Source/storm.cpp
  3rdParty/Storm/Source/storm.h
  Source/monster.cpp
  Source/movie.cpp
Labels: Binary exact

#365 Finish cleaning player.cpp
  Source/items.cpp
  Source/items.h
  Source/player.cpp
Labels: Binary exact

#375 effects_cleanup_sfx & stream_update
  Source/effects.cpp
  Source/effects.h
  structs.h
Labels: Binary exact

#357 clean all tmsg functions
  Source/tmsg.cpp
  Source/tmsg.h
  structs.h
Labels: Binary exact

#400 Monster.cpp
  Source/control.cpp
  Source/cursor.cpp
  Source/diablo.cpp
  Source/diablo.h
  Source/missiles.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/multi.cpp
  Source/objects.cpp
  structs.h
Labels: Binary exact

#402 Monster.cpp
  Source/dead.cpp
  Source/missiles.cpp
  Source/monster.cpp
  Source/monster.h
  enums.h
Labels: Binary exact

#396 Control.cpp
  Source/control.cpp
  Source/control.h
  Source/inv.cpp
  Source/items.cpp
  Source/monster.cpp
  Source/objects.cpp
  Source/scrollrt.cpp
  Source/town.cpp
Labels: Binary exact

#412 clean and format portal.cpp
  Source/portal.cpp
  Source/portal.h
  structs.h
Labels: Binary exact

#422 Error
  Source/error.cpp
  Source/error.h
Labels: Binary exact

#430 Gamemenu.cpp
  Source/automap.cpp
  Source/control.cpp
  Source/cursor.cpp
  Source/diablo.cpp
  Source/diablo.h
  Source/gamemenu.cpp
  Source/gendung.cpp
  Source/gendung.h
  Source/gmenu.cpp
  Source/gmenu.h
  Source/interfac.cpp
  Source/inv.cpp
  Source/lighting.cpp
  Source/loadsave.cpp
  Source/mainmenu.cpp
  Source/mainmenu.h
  Source/missiles.cpp
  Source/multi.cpp
  Source/objects.cpp
  Source/palette.cpp
  Source/palette.h
  Source/player.cpp
  Source/portal.cpp
  Source/scrollrt.cpp
  Source/scrollrt.h
  Source/stores.cpp
  Source/themes.cpp
  Source/trigs.cpp
  enums.h
Labels: Binary exact

#439 Fix NULL check on MType
  Source/monster.cpp
Labels: bug

#436 monster.cpp
  Source/monster.cpp
  Source/monster.h
Labels: Binary exact

#424 encrypt.cpp
  Source/encrypt.cpp
  Source/encrypt.h
  structs.h
Labels: Binary exact

#435 Capture.cpp
  Source/capture.cpp
  Source/capture.h
Labels: Binary exact

#442 Monster.cpp
  Source/cursor.cpp
  Source/missiles.cpp
  Source/monster.cpp
  Source/player.cpp
  Source/scrollrt.cpp
  enums.h
Labels: Binary exact

#445 Cleanup UseItem
  Source/items.cpp
  structs.h
Labels: Binary exact

#443 Monster.cpp
  Source/control.cpp
  Source/control.h
  Source/items.cpp
  Source/missiles.cpp
  Source/monster.cpp
  Source/monster.h
  Source/objects.cpp
  Source/player.cpp
  enums.h
Labels: Binary exact
