Repository diasurgical/devilution, pull requests merged in 2018-11, with the labels that each got.

#454 Fix level 16 message
  Source/player.cpp
Labels: bug

#468 Clean up MAI_Garg
  Source/monster.cpp
Labels: Binary exact

#470 M teleport
  Source/missiles.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/msg.h
  Source/multi.cpp
  Source/multi.h
Labels: Binary exact

#472 Clean up MAI_SkelSd
  Source/monster.cpp
Labels: Binary exact

#473 Mai skel bow
  Source/monster.cpp
Labels: Binary exact

#474 Clean up MAI_Fat
  Source/monster.cpp
Labels: Binary exact

#476 monster.cpp
  Source/monster.cpp
  Source/monster.h
Labels: Binary exact

#482 CheckDungeonClear binary exact
  Source/debug.cpp
Labels: Binary exact

#483 dthread_send_delta almost bin exact
  Source/dthread.cpp
Labels: Minimal differences

#481 mainmenu_loop bin exact
  Source/mainmenu.cpp
Labels: Binary exact

#475 Clean up MAI_Warlord
  Source/monster.cpp
Labels: Minimal differences

#478 Clean up PosOkMonst3
  Source/monster.cpp
Labels: Minimal differences
