Repository diasurgical/devilution, pull requests merged in 2019-09, with the labels that each got.

#1481 random bin exact in vanilla/hellfire
  Source/engine.cpp
Labels: Binary exact, code cleanup, hellfire

#1442 Clean up init_disable_screensaver
  Source/automap.cpp
  Source/control.cpp
  Source/drlg_l1.cpp
  Source/init.cpp
Labels: code cleanup

#1486 DRLG_L3.cpp bin exact
  Source/drlg_l3.cpp
  Source/drlg_l3.h
Labels: Binary exact, hellfire

#1488 Wave.cpp bin exact
  Source/wave.cpp
Labels: Binary exact, hellfire

#1467 [hellfire] log_printf bin exact
  Source/logging.cpp
Labels: Binary exact, hellfire

#1491 DRLG_L5 cleanups (Crypt support)
  Source/drlg_l1.cpp
  Source/drlg_l1.h
  Source/gendung.cpp
  Source/items.cpp
  Source/items.h
  Source/multi.cpp
Labels: Binary exact, hellfire

#1493 [hellfire] DRLG_L4 bin exact
  Source/drlg_l4.cpp
Labels: Binary exact, code cleanup, hellfire

#1492 More drlg_l1 functions
  Source/drlg_l1.cpp
Labels: Binary exact, hellfire

#1495 Add Icon/Workspace for Hellfire
  Hellfire.dsp
  Hellfire.dsw
  Hellfire.ico
  Hellfire.rc
Labels: hellfire

#1494 [hellfire] ClearPlrRVars
  Source/player.cpp
Labels: Binary exact, hellfire

#1499 Clean up AddPlrMonstExper
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1502 InitMonster fin bexact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1505 AddGuardian cleanup
  Source/missiles.cpp
Labels: code cleanup

#1506 [hellfire] AddManashield bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1507 AddApoca cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1510 AddElement cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1515 AddAcidpud cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1516 AddFireball cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1513 [hellfire] AddMagmaball bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1514 [hellfire] AddAcid bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1517 AddInfra cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1521 AddFlame cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1529 [hellfire] MI_Apoca bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1518 AddNova cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1519 AddEtherealize cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1520 AddFlash2 cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1522 AddFlamec cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1523 Sentfire cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1524 MI_Lightball cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1526 MI_Hbolt cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1527 MI_Flame cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1528 MI_Flamec cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1530 [hellfire] MI_Stone bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1531 MI_Acidsplat cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1532 MI_Teleport cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1533 [hellfire] AddFirewallC bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1542 [hellfire] PlaceThemeMonsts bin exact
  Source/themes.cpp
Labels: Binary exact, hellfire

#1534 miss_null_1D cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1535 AddTown cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup

#1539 [hellfire] MI_Guardian bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1540 MI_Firemove cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1541 Theme_Library cleanup
  Source/themes.cpp
Labels: Binary exact, code cleanup, hellfire

#1538 MI_Etherealize cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1537 [hellfire] AddFlare bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1489 [hellfire] GetPlrGFXSize
  Source/player.cpp
Labels: Binary exact, hellfire

#1490 [hellfire] SetPlrAnims
  Source/player.cpp
  Source/player.h
Labels: Binary exact, hellfire

#1498 [hellfire] NextPlrLevel
  Source/player.cpp
Labels: Binary exact, hellfire

#1503 Add the e variable to AddPlrMonstExper
  Source/player.cpp
Labels: code cleanup

#1508 [hellfire] SolidLoc
  Source/player.cpp
Labels: Binary exact, hellfire

#1509 Clean up PM_ChangeLightOff
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1525 MI_Fireball cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1544 [hellfire] AddGuardian bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1545 [hellfire] AddTown bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1546 AddFlash cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1547 MI_Golem cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup

#1548 MI_LArrow cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1554 SetPortalStats bin exact vanilla
  Source/portal.cpp
Labels: Binary exact, code cleanup, hellfire

#1553 mpqapi_add_file cleanup
  Source/mpqapi.cpp
Labels: Binary exact, code cleanup, hellfire

#1557 [hellfire] SaveGamma bin exact
  Source/palette.cpp
Labels: Binary exact, hellfire

#1556 [hellfire] LoadGamma bin exact
  Source/palette.cpp
Labels: Binary exact, hellfire

#1555 PrintPlrMsg cleanup
  Source/plrmsg.cpp
Labels: Binary exact, code cleanup, hellfire

#1560 Fix GetItemAttrs
  Source/items.cpp
Labels: Binary exact, hellfire

#1500 [hellfire] diablo_get_not_running bin exact
  Source/diablo.cpp
Labels: Binary exact, hellfire

#1561 bin exact on UseStaff
  Source/inv.cpp
Labels: Binary exact, hellfire

#1563 DrawInv
  Source/inv.cpp
Labels: Binary exact, hellfire

#1562 Clean up RemovePlrMissiles
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1573 [hellfire] RndHealerItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1572 [hellfire] SpawnHealer bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1571 ItemNoFlippy cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1564 [hellfire] RndLocOk bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1565 [hellfire] SyncCrux bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1566 BreakCrux cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup

#1567 [hellfire] MI_Misexp bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1569 RecreateSmithItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1570 RecreateHealerItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1568 [hellfire] ProcessMissiles bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1575 Add music code+quest
  Source/diablo.cpp
  Source/items.cpp
  Source/items.h
  Source/mainmenu.cpp
  Source/objects.cpp
  Source/objects.h
  Source/sound.cpp
  enums.h
Labels: Binary exact, hellfire

#1576 [hellfire] stream_update bin exact
  Source/effects.cpp
Labels: Binary exact, hellfire

#1577 M_CheckEFlag
  Source/monster.cpp
Labels: Binary exact, hellfire

#1578 [hellfire] M_ClearSquares bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1580 [hellfire] M_StartKill bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1585 [hellfire] M_DoStand bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1584 [hellfire] M_StartHeal bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1583 [hellfire] M_StartFadeout bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1582 [hellfire] M_StartFadein bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1581 [hellfire] M_SyncStartKill bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1588 path_next_node cleanup
  Source/path.cpp
Labels: Binary exact, code cleanup, hellfire

#1590 PindFath
  Source/path.cpp
Labels: Binary exact, code cleanup, hellfire

#1589 CheckCursMove bin exact
  Source/cursor.cpp
  defs.h
  structs.h
Labels: Binary exact, code cleanup, hellfire

#1511 [hellfire] AddArrow bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1579 M_GetKnockback cleanup
  Source/monster.cpp
Labels: Binary exact, code cleanup, hellfire

#1551 [hellfire] AddLArrow bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1608 [hellfire] RndSmithItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1607 [hellfire] SmithItemOk bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1611 [hellfire] RndWitchItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1614 [hellfire] CreateTown bin exact
  Source/town.cpp
Labels: Binary exact, hellfire

#1613 [hellfire] RndPremiumItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1610 [hellfire] RndBoyItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1621 [hellfire] CheckQuestKill bin exact
  Source/quests.cpp
Labels: Binary exact, hellfire

#1622 [hellfire] TownCtrlMsg bin exact
  Source/towners.cpp
Labels: Binary exact, hellfire

#1625 [hellfire] InitFarmer bin exact
  Source/towners.cpp
  Source/towners.h
  enums.h
Labels: Binary exact, hellfire

#1624 NewTownerAnim cleanup
  Source/towners.cpp
Labels: Binary exact, code cleanup, hellfire

#1627 [hellfire] 6 towners.cpp functions bin exact
  Source/towners.cpp
  Source/towners.h
Labels: Binary exact, hellfire

#1623 Apply enums to quests
  Source/drlg_l2.cpp
  Source/drlg_l4.cpp
  Source/town.cpp
  Source/towners.cpp
Labels: code cleanup

#1620 ResyncQuests cleanup
  Source/quests.cpp
Labels: Binary exact, code cleanup, hellfire

#1619 [hellfire] ResyncMPQuests bin exact
  Source/quests.cpp
Labels: Binary exact, hellfire

#1618 SetReturnLvlPos cleanup
  Source/quests.cpp
Labels: Binary exact, code cleanup, hellfire

#1616 InitThemes cleanup
  Source/themes.cpp
Labels: Binary exact, code cleanup, hellfire

#1615 [hellfire] BreakCrux bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1600 [hellfire] InitControlPan bin exact
  Source/control.cpp
Labels: Binary exact, hellfire

#1629 [hellfire] DoResurrect bin exact
  Source/spells.cpp
Labels: Binary exact, hellfire

#1630 [hellfire] CreateRndItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1631 [hellfire] CreateRndUseful bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1633 [hellfire] SpawnQuestItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1634 [hellfire] SpawnRock bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1635 [hellfire] AddInitItems bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1641 CalcPlrItemMin cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1652 SortWitch cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1653 SortHealer cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1654 SortSmith cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1644 RecreateEar cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1656 [hellfire] InitRndBarrels bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1655 [hellfire] town.cpp - 4 functions bin exact
  Source/town.cpp
  Source/town.h
Labels: Binary exact, hellfire

#1649 [hellfire] CalcPlrBookVals bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1648 [hellfire] PrintItemMisc bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1643 [hellfire] FreeItemGFX bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1642 [hellfire] SetPlrHandItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1647 ProcessItems cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1646 GetUniqueItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1645 SetupItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1637 [hellfire] RndAllItems bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1638 [hellfire] SpawnUnique bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1639 [hellfire] CreateItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1640 [hellfire] items.cpp - 4 functions bin exact
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1651 [hellfire] items.cpp - 5 functions bin exact
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1609 [hellfire] PremiumItemOk bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1636 [hellfire] RndUItem bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1658 [hellfire] CowSFX bin exact
  Source/towners.cpp
Labels: Binary exact, hellfire

#1657 [hellfire] SpawnSmith bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1659 [hellfire] M_StartWalk2 bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1660 [hellfire] M_StartWalk3 bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1662 Cleanup trigs.cpp
  Source/trigs.cpp
  defs.h
Labels: Binary exact, hellfire

#1650 Fix S_StartTalk
  Source/stores.cpp
Labels: Binary exact, bug

#1665 Town/misc fixes
  Source/control.cpp
  Source/diablo.cpp
  Source/diablo.h
  Source/stores.cpp
  Source/stores.h
  Source/town.cpp
  Source/towners.cpp
Labels: Binary exact, hellfire

#1663 MAI_Snake
  Source/monster.cpp
Labels: Binary exact, code cleanup, hellfire

#1666 [hellfire] gmenu_init_menu bin exact
  Source/gmenu.cpp
Labels: Binary exact, hellfire

#1667 gmenu_clear_buffer cleanup
  Source/gmenu.cpp
Labels: Binary exact, code cleanup, hellfire

#1669 SetSpell cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#1671 Freeupstairs cleanup
  Source/trigs.cpp
Labels: Binary exact, code cleanup, hellfire

#1670 [hellfire] gmenu_draw_menu_item bin exact
  Source/gmenu.cpp
Labels: Binary exact, hellfire
