Repository diasurgical/devilution, pull requests merged in 2019-10, with the labels that each got.

#1764 [hellfire] ClrAllObjects
  Source/objects.cpp
Labels: Binary exact, hellfire

#1765 AddArmorStand cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1766 AddWeaponRack cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1767 [hellfire] AddChestTraps bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1769 [hellfire] Obj_BCrossDamage bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1771 miss_null_32 cleanup
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#1773 [hellfire] items.cpp
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1776 GetStaffPower cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#1775 [hellfire] GetStaffSpell
  Source/items.cpp
Labels: Binary exact, hellfire

#1778 some automap
  Source/automap.cpp
  Source/automap.h
Labels: Binary exact, hellfire

#1779 [hellfire] SearchAutomapItem bin exact
  Source/automap.cpp
  Source/automap.h
Labels: Binary exact, hellfire

#1777 [hellfire] GetAutomapType bin exact
  Source/automap.cpp
Labels: Binary exact, hellfire

#1781 enums
  Source/debug.cpp
  Source/drlg_l2.cpp
  Source/drlg_l3.cpp
  Source/inv.cpp
  Source/items.cpp
Labels: code cleanup

#1787 [hellfire] InitItems / items_42390F bin exact
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1785 scrollrt_draw_lower cleanup
  Source/scrollrt.cpp
Labels: Binary exact, code cleanup, hellfire

#1784 scrollrt_draw_lower_2 cleanup
  Source/scrollrt.cpp
Labels: Binary exact, code cleanup, hellfire

#1786 [hellfire] DrawClippedObject bin exact
  Source/scrollrt.cpp
Labels: Binary exact, hellfire

#1783 [hellfire] DrawObject bin exact
  Source/scrollrt.cpp
Labels: Binary exact, hellfire

#1782 [hellfire] DrawMissile/DrawClippedMissile bin exact
  Source/scrollrt.cpp
Labels: Binary exact, hellfire

#1717 Itemdat
  Source/itemdat.cpp
  Source/itemdat.h
  enums.h
Labels: hellfire

#1774 [hellfire] items.cpp_2
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1780 DrawAutomapType cleanup
  Source/automap.cpp
Labels: Binary exact, code cleanup, hellfire

#1768 DIABOOL
  Source/doom.cpp
  Source/doom.h
  Source/init.cpp
  Source/objects.cpp
  Source/objects.h
  defs.h
Labels: Binary exact, code cleanup, enhancement, hellfire, help wanted

#1770 apply enums
  Source/diablo.cpp
  Source/diablo.h
  Source/items.cpp
  Source/missiles.cpp
  Source/objects.cpp
  Source/pack.cpp
  Source/stores.cpp
  structs.h
Labels: code cleanup

#1789 more enums
  Source/gendung.cpp
  Source/monster.cpp
  Source/objects.cpp
Labels: code cleanup

#1711 [hellfire] MI_Manashield bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1735 [hellfire] DoHealOther bin exact
  Source/spells.cpp
Labels: Binary exact, hellfire

#1738 [hellfire] InitMonsterGFX bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1747 [hellfire] AddBlodboil bin exact
  Source/missiles.cpp
  Source/missiles.h
Labels: Binary exact, hellfire, invalid

#1748 [hellfire] MI_Blodboil bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire, invalid

#1360 Ui consts
  Source/control.cpp
  Source/inv.cpp
  defs.h
Labels: code cleanup

#1772 [hellfire] gamemenu_save_game / gamemenu_load_game bin exact
  Source/gamemenu.cpp
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire, invalid

#1550 [hellfire] AddRndTeleport bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1790 [hellfire] GetDamageAmt bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1612 [hellfire] WitchItemOk bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1792 [hellfire] game_2_ui_class / pfile_get_player_class bin exact
  Source/pfile.cpp
  enums.h
Labels: Binary exact, hellfire

#1793 Small bug in GetDamageAmt
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1791 [hellfire] GetManaAmount bin exact
  Source/spells.cpp
Labels: Binary exact, hellfire

#1795 [hellfire] GetBookSpell bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1797 [hellfire] PlayDungMsgs bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1796 [hellfire] 3 functions bin exact
  Source/player.cpp
  Source/player.h
Labels: Binary exact, hellfire

#1798 [hellfire] OperateMushPatch bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1803 Fix function order [drlg_l1.cpp]
  Source/drlg_l1.cpp
  Source/drlg_l1.h
Labels: code cleanup

#1805 Fix function order [drlg_l3.cpp]
  Source/drlg_l3.cpp
  Source/drlg_l3.h
  comparer-config/diablo.toml
Labels: code cleanup

#1806 Fix function order [drlg_l4.cpp]
  Source/drlg_l4.cpp
  Source/drlg_l4.h
Labels: code cleanup

#1808 [hellfire] PlaceMonster bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1809 [hellfire] M_ChangeLightOffset bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1815 PlrHasItem: pass by reference
  Source/monster.cpp
  Source/objects.cpp
  Source/towners.cpp
  Source/towners.h
Labels: code cleanup

#1818 Fix function order [dx.cpp]
  Source/dx.cpp
  Source/dx.h
  Source/scrollrt.cpp
Labels: code cleanup
