Repository diasurgical/devilution, pull requests merged in 2019-11, with the labels that each got.

#1837 Fix function order [spells+pack.cpp]
  Source/pack.cpp
  Source/pack.h
  Source/spells.cpp
  Source/spells.h
Labels: code cleanup

#1843 Fix function order [gendung.cpp]
  Source/gendung.cpp
  Source/gendung.h
Labels: code cleanup

#1846 Fix function order [palette.cpp]
  Source/palette.cpp
  Source/palette.h
Labels: code cleanup

#1851 [hellfire] fix drlg_l4 functions
  Source/drlg_l4.cpp
Labels: Binary exact, code cleanup, hellfire

#1852 [hellfire] fix drlg_l1 functions
  Source/drlg_l1.cpp
Labels: Binary exact, code cleanup, hellfire

#1854 AddL1Door cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1858 Obj_Trap cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1857 AddMagicCircle cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1859 [hellfire] Obj_Light bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1853 [hellfire] AddTrap bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1855 [hellfire] TorchLocOK bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1863 [hellfire] OperateLever bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1862 [hellfire] ObjChangeMap bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1861 [hellfire] ObjChangeMapResync bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1856 [hellfire] WallTrapLocOk bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1860 [hellfire] GetRndObjLoc bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1864 [hellfire] add_crypt_objs bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1865 apply TRUE/FALSE
  Source/objects.cpp
Labels: code cleanup

#1866 apply enum to max shrines
  Source/objects.cpp
Labels: code cleanup
