Repository diasurgical/devilution, pull requests merged in 2019-08, with the labels that each got.

#1355 Clean multi_send_zero_packet right
  Source/multi.cpp
  Source/multi.h
Labels: Binary exact

#1367 [spawn] make GetPlrGFXSize bin exact
  Source/player.cpp
Labels: Binary exact

#1444 [hellfire] init_archives, init_cleanup and items_get_currlevel
  Source/effects.cpp
  Source/init.cpp
  Source/items.cpp
  Source/items.h
  Source/objects.cpp
  enums.h
Labels: Binary exact, hellfire

#1451 [hellfire] On_ENDREFLECT
  Source/msg.cpp
  enums.h
Labels: Binary exact, hellfire

#1448 [hellfire] MI_Chain bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1454 [hellfire] ModifyPlrMag bin exact
  Source/player.cpp
  enums.h
Labels: Binary exact, hellfire

#1455 [hellfire] ModifyPlrDex bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1460 [hellfire] SetPlrVit bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1463 Fix returning in MonsterTrapHit
  Source/missiles.cpp
Labels: Binary exact

#1464 applied enums to _pmode and untangled ifs
  Source/missiles.cpp
  Source/player.cpp
  Source/scrollrt.cpp
  Source/spells.cpp
Labels: code cleanup

#1458 [hellfire] SetPlrMag bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1457 [hellfire] SetPlrStr bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1469 [hellfire] AddHeal bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1456 [hellfire] ModifyPlrVit bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1459 [hellfire] SetPlrDex bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1461 [hellfire] InitDungMsgs bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1470 [hellfire] init_read_test_file bin exact
  Source/init.cpp
  Source/pfile.cpp
Labels: Binary exact, code cleanup, hellfire

#1468 [hellfire] FindClosest bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1462 [hellfire] UseMana bin exact
  Source/spells.cpp
Labels: Binary exact, hellfire

#1449 [hellfire] RestartTownLvl bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1473 [hellfire] CreatePlrItems bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1466 Apply enums to _mFlags
  Source/missiles.cpp
  Source/scrollrt.cpp
Labels: code cleanup

#1478 [hellfire] InitCursor and FreeCursor bin exact
  Source/cursor.cpp
  Source/cursor.h
Labels: Binary exact, hellfire

#1480 Add preliminary Crypt/Hive support
  Source/cursor.cpp
  Source/diablo.cpp
  Source/diablo.h
  Source/drlg_l1.cpp
  Source/palette.cpp
Labels: Binary exact, hellfire
