Repository diasurgical/devilution, pull requests merged in 2019-12, with the labels that each got.

#1868 [capture.cpp] fix functions
  Source/capture.cpp
Labels: Binary exact, code cleanup, hellfire

#1869 Fix type for panelstr
  Source/control.cpp
  Source/control.h
Labels: code cleanup

#1870 Fix function order [capture.cpp]
  Source/capture.cpp
  Source/capture.h
Labels: Binary exact, code cleanup

#1871 Fix all "pass by ref" functions
  Source/items.cpp
  Source/items.h
  Source/missiles.cpp
  Source/monster.cpp
  Source/monster.h
  Source/objects.cpp
  Source/objects.h
  Source/player.cpp
Labels: code cleanup

#1823 some cleanup
  Source/control.cpp
Labels: code cleanup

#1872 Fix missing assert for FindGetItem
  README.md
  Source/inv.cpp
Labels: code cleanup

#1873 [hellfire] palette_init bin exact
  Source/palette.cpp
Labels: Binary exact, hellfire, help wanted

#1876 [hellfire] palette_update_crypt , hive bin exact
  Source/palette.cpp
  Source/palette.h
Labels: Binary exact, hellfire, help wanted

#1877 sound_DirectSoundCreate cleanup
  Source/sound.cpp
Labels: Binary exact, code cleanup, hellfire

#1878 snd_init cleanup
  Source/sound.cpp
Labels: Binary exact, code cleanup, hellfire

#1879 Fix scrollrt draw cursor back
  Source/scrollrt.cpp
Labels: Binary exact, code cleanup, hellfire

#1884 lighting_color_cycling cleanup
  Source/lighting.cpp
Labels: Binary exact, code cleanup, hellfire

#1883 [hellfire] ProcessPlayers bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1886 [hellfire] comparer config - fix lighting_color_cycling size
  comparer-config/hellfire.toml
Labels: hellfire

#1885 [hellfire] SyncInitPlrPos bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1887 [hellfire] InitPlayer bin exact
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire
