Repository diasurgical/devilution, pull requests merged in 2020-10, with the labels that each got.

#2073 DrawChr cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup

#2075 DoSpeedBook cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2076 DoPanBtn cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2077 control_check_btn_press cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2078 CheckChrBtns cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2079 CheckSBook cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2080 DrawGoldSplit cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2081 control_print_talk_msg cleanup
  Source/control.cpp
Labels: Binary exact, code cleanup, hellfire

#2091 RndItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup

#2093 PlrHitPlr cleanup
  Source/player.cpp
Labels: Binary exact, code cleanup

#2092 CalcSelfItems cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#2089 RechargeItem cleanup
  Source/items.cpp
Labels: Binary exact, code cleanup, hellfire

#2086 nthread_send_and_recv_turn cleanup
  Source/nthread.cpp
Labels: Binary exact, code cleanup, hellfire

#2094 CheckNewPath cleanup
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#2084 apply ear enum
  Source/sync.cpp
Labels: code cleanup

#2082 [hellfire] sync_monster cleanup
  Source/sync.cpp
Labels: Binary exact, hellfire

#2101 sizeof instead of hardcoded size
  Source/multi.cpp
Labels: code cleanup

#2095 FindValidShrine cleanup + enums
  Source/objects.cpp
  enums.h
Labels: Binary exact, code cleanup, hellfire

#2098 BreakBarrel cleanup
  Source/objects.cpp
Labels: code cleanup

#2100 Ear cleanup #2
  Source/items.cpp
  Source/msg.cpp
  Source/pack.cpp
Labels: code cleanup

#2090 [hellfire] HealerItemOk bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#2097 apply DIABOOLS
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#2088 apply enums
  Source/items.cpp
  Source/objects.cpp
Labels: code cleanup

#2096 OperateFountains cleanup
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#2087 [hellfire] nthread_recv_turns bin exact
  Source/nthread.cpp
Labels: Binary exact, hellfire

#2099 some cleanups
  Source/automap.cpp
  Source/drlg_l2.cpp
  Source/drlg_l4.cpp
  Source/inv.cpp
  Source/lighting.cpp
  Source/missiles.cpp
  Source/msg.cpp
  Source/objects.cpp
  Source/player.cpp
  Source/portal.cpp
  Source/quests.cpp
  Source/quests.h
  Source/render.cpp
  Source/scrollrt.cpp
  Source/stores.cpp
  Source/towners.cpp
  enums.h
  structs.h
Labels: code cleanup

#2103 [hellfire] RightMouseDown bin exact
  Source/diablo.cpp
Labels: Binary exact, hellfire

#2104 [hellfire] AddMisexp bin exact
  Source/missiles.cpp
Labels: Binary exact, hellfire

#2105 path_get_node1 cleanup
  Source/path.cpp
Labels: Binary exact, code cleanup, hellfire

#2106 path_get_node2 cleanup
  Source/path.cpp
Labels: Binary exact, code cleanup, hellfire

#2107 Theme_MonstPit cleanup
  Source/themes.cpp
Labels: Binary exact, code cleanup, hellfire

#2110 [hellfire] DrawChr bin exact
  Source/control.cpp
Labels: Binary exact, hellfire

#2108 GetErrorStr cleanup
  Source/appfat.cpp
Labels: Binary exact, code cleanup, hellfire

#2109 AddFirewall cleanup
  Source/missiles.cpp
Labels: code cleanup

#2112 [hellfire] mainmenu_play_intro
  Source/mainmenu.cpp
Labels: Binary exact, hellfire

#2111 [hellfire] DrawSpellList bin exact
  Source/control.cpp
Labels: Binary exact, hellfire

#2114 some defines
  Source/multi.cpp
  defs.h
Labels: code cleanup

#2115 [hellfire] door fix
  Source/objects.cpp
  defs.h
Labels: Binary exact, hellfire

#2116 more cleanup
  Source/objects.cpp
Labels: code cleanup

#2123 Stores
  Source/stores.cpp
  Source/stores.h
  defs.h
Labels: hellfire

#2121 Load hellfire spells from hero save
  Source/pack.cpp
Labels: hellfire

#2122 Implement loading of hellfire object files
  Source/objdat.cpp
  Source/objdat.h
  Source/objects.cpp
Labels: hellfire

#2128 On_SBSPELL cleanup
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2129 delta_get_item cleanup
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2131 DeltaImportData bin exact and cleanup
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2130 On_SPELLXYD cleanup
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2127 cleanup
  Source/missiles.cpp
  Source/monster.cpp
  Source/multi.cpp
  Source/objects.cpp
  Source/player.cpp
Labels: code cleanup

#2134 DeltaAddItem
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2133 some magic numbers cleanup
  Source/msg.cpp
Labels: code cleanup

#2132 enums and cleanups
  Source/msg.cpp
  Source/nthread.cpp
  Source/wave.cpp
  defs.h
Labels: Binary exact, code cleanup, hellfire

#2135 fix multi quest bug
  Source/msg.cpp
Labels: bug

#2136 delta_init bin exact
  defs.h
Labels: Binary exact, code cleanup, hellfire

#2137 unify names
  Source/missiles.cpp
  Source/monstdat.cpp
  Source/monster.cpp
  enums.h
Labels: code cleanup
