Repository diasurgical/devilution, pull requests merged in 2020-01, with the labels that each got.

#1895 [hellfire] monster_some_crypt bin exact
  Source/monster.cpp
  Source/monster.h
Labels: Binary exact, hellfire

#1896 [hellfire] PlaceUniqueMonst bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire, help wanted

#1897 [hellfire] PlaceQuestMonsters bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1898 [hellfire] CanTalkToMonst bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1899 [hellfire] TalktoMonster bin exact
  Source/monster.cpp
Labels: Binary exact, hellfire

#1900 [hellfire] GetSBookTrans bin exact
  Source/control.cpp
Labels: Binary exact, hellfire

#1902 gamemenu_gamma cleanup
  Source/gamemenu.cpp
Labels: Binary exact, code cleanup, hellfire

#1917 [hellfire] DoorSet bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1916 SyncDoors cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1913 OperateTrapLvr cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1904 [hellfire] OperateInnSignChest bin exact
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1905 [hellfire] OperateWeaponRack bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#1906 OperateCauldron cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1907 add hellfire shrine enums
  enums.h
Labels: hellfire

#1909 [hellfire] OperateDecap bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1908 [hellfire] OperateArmorStand bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#1910 [hellfire] OperateBookCase bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#1911 [hellfire] OperateSkelBook bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#1912 [hellfire] OperateSarc bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1914 [hellfire] SyncOpL1Door bin exact
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1915 [hellfire] SyncOpL2Door, SyncOpL3Door bin exact
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1903 [hellfire] gamemenu_music_volume bin exact
  Source/gamemenu.cpp
Labels: Binary exact, code cleanup, hellfire

#1919 Obj_Circle cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire, help wanted

#1920 SetupObject cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1921 Lets give them somthing to talk about 🎵
  Source/textdat.cpp
  Source/textdat.h
Labels: Binary exact, hellfire

#1923 ProcessObjects cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1924 AddObject cleanup
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1928 [hellfire] OperateChest bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, code cleanup, hellfire

#1927 [hellfire] OperateSChambBk bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1926 [hellfire] OperateBook bin exact
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1929 [hellfire] TryDisarm bin exact
  Source/objects.cpp
Labels: Binary exact, hellfire

#1925 [hellfire] OperateL1RDoor bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1930 [hellfire] AddShrine bin exact
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1931 [hellfire] OperateShrine
  Source/objects.cpp
  enums.h
Labels: hellfire

#1932 SyncPlrAnim clean up
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1933 [hellfire] PM_ChangeOffset
  Source/gamemenu.cpp
  Source/gamemenu.h
  Source/player.cpp
Labels: Binary exact, hellfire

#1937 Align PM_DoWalk, PM_DoWalk2 and PM_DoWalk3
  Source/player.cpp
Labels: code cleanup

#1941 [hellfire] TryIconCurs && DoOil
  Source/diablo.cpp
  Source/items.cpp
  Source/items.h
Labels: Binary exact, hellfire

#1936 Correct spelling of color
  Source/diablo.cpp
  Source/gamemenu.cpp
  Source/inv.cpp
  Source/palette.cpp
  Source/palette.h
  comparer-config/diablo.toml
Labels: code cleanup

#1943 [hellfire] diablo_color_cyc_logic
  Source/diablo.cpp
  Source/palette.cpp
  Source/palette.h
Labels: Binary exact, hellfire

#1944 [hellfire] PM_DoWalk and PM_DoWalk3
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1947 [hellfire] diablo_parse_flags
  Source/diablo.cpp
Labels: Binary exact, hellfire

#1939 [hellfire] StartGame
  Source/diablo.cpp
  Source/inv.cpp
  Source/inv.h
  comparer-config/hellfire.toml
Labels: Binary exact, hellfire

#1940 DisableInputWndProc clean up
  Source/diablo.cpp
Labels: Binary exact, code cleanup, hellfire

#1953 [hellfire] some loop fixes
  Source/objects.cpp
Labels: Binary exact, code cleanup, hellfire

#1945 [hellfire] PressChar
  Source/diablo.cpp
Labels: Binary exact, hellfire

#1942 PressKey clean up
  Source/diablo.cpp
Labels: Binary exact, code cleanup, hellfire

#1946 [hellfire] WinMain
  Source/diablo.cpp
  Source/diablo.h
Labels: Binary exact, hellfire

#1950 [hellfire] SetupTownStores and SmithBuyPItem
  Source/debug.cpp
  Source/items.cpp
  Source/items.h
  Source/stores.cpp
Labels: Binary exact, hellfire

#1952 MAXQUESTS variable
  Source/stores.cpp
  Source/towners.cpp
Labels: Binary exact, code cleanup, hellfire

#1957 [hellfire] OperateL1LDoor bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1958 [hellfire] OperateStoryBook bin exact
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1964 enums and stuff
  DiabloUI/diabloui.cpp
  Source/control.cpp
  Source/control.h
  Source/debug.cpp
  Source/diablo.cpp
  Source/gendung.cpp
  Source/gmenu.cpp
  Source/help.cpp
  Source/help.h
  Source/inv.cpp
  Source/items.cpp
  Source/logging.cpp
  Source/missiles.cpp
  Source/mpqapi.cpp
  Source/nthread.cpp
  Source/objects.cpp
  Source/stores.cpp
  Source/themes.cpp
Labels: code cleanup, help wanted

#1969 tMsgSaid type change
  Source/towners.cpp
  structs.h
Labels: code cleanup

#1967 Add network commands and cursors
  Source/cursor.cpp
  Source/cursor.h
  Source/inv.cpp
  Source/msg.cpp
  Source/msg.h
  enums.h
Labels: hellfire

#1970 Fix items and cutscenes
  Source/interfac.cpp
  Source/items.cpp
  Source/items.h
  Source/scrollrt.cpp
  defs.h
Labels: hellfire

#1971 Fix hellfire hive/crypt
  Source/multi.cpp
Labels: hellfire

#1973 Fix inventory drawing and missiles
  Source/inv.cpp
  Source/misdat.cpp
Labels: hellfire

#1976 Fixspellicons
  Source/control.cpp
Labels: hellfire

#1980 DrawZoom cleanup
  Source/scrollrt.cpp
Labels: Binary exact, code cleanup, hellfire

#1979 [hellfire] DrawGame bin exact
  Source/scrollrt.cpp
Labels: Binary exact, hellfire

#1977 [hellfire] OilItem
  Source/items.cpp
Labels: Binary exact, hellfire

#1978 [hellfire] PrintItemPower
  Source/items.cpp
  enums.h
Labels: hellfire

#1984 [hellfire] mi_light_ring
  Source/missiles.cpp
Labels: Binary exact, hellfire

#1983 [hellfire] StartPlayerKill bin exact
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#1982 [hellfire] WeaponDur bin exact
  Source/player.cpp
Labels: Binary exact, hellfire

#1985 [hellfire] StripTopGold bin exact
  Source/player.cpp
  Source/player.h
Labels: Binary exact, hellfire

#1986 [hellfire] InitItemGFX bin exact
  Source/items.cpp
Labels: Binary exact, hellfire

#1988 [hellfire] monster_43C785
  Source/monster.cpp
  Source/monster.h
Labels: Binary exact, hellfire

#1991 [hellfire] new functions
  Source/objects.cpp
  Source/objects.h
Labels: Binary exact, hellfire

#1995 [hellfire] missiles_steal_pots
  Source/missiles.cpp
Labels: hellfire

#1997 use enums
  Source/control.cpp
  Source/debug.cpp
  Source/diablo.cpp
  Source/inv.cpp
  Source/objects.cpp
  Source/pack.cpp
  Source/stores.cpp
  Source/sync.cpp
Labels: code cleanup
