Repository diasurgical/devilution, pull requests merged in 2020-12, with the labels that each got.

#2163 Goe
  Source/drlg_l1.cpp
  Source/drlg_l3.cpp
  Source/itemdat.cpp
  Source/items.cpp
  Source/missiles.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/objects.cpp
  Source/player.cpp
  Source/portal.cpp
  Source/quests.cpp
  Source/spells.cpp
  Source/themes.cpp
  enums.h
Labels: code cleanup

#2162 spell defines and macros
  Source/control.cpp
  Source/debug.cpp
  Source/inv.cpp
  Source/items.cpp
  Source/objects.cpp
  Source/player.cpp
  defs.h
Labels: code cleanup

#2167 some cleanup
  Source/items.cpp
  Source/missiles.cpp
Labels: code cleanup

#2168 [hellfire] CheckInvPaste
  Source/inv.cpp
Labels: hellfire

#2169 [hellfire] Highlight items during search
  Source/scrollrt.cpp
Labels: Binary exact, hellfire

#2173 [hellfire] SpawnOnePremium
  Source/items.cpp
  Source/items.h
  Source/player.cpp
  Source/player.h
  comparer-config/hellfire.toml
Labels: Binary exact, hellfire

#2172 [hellfire] UseItem
  Source/items.cpp
Labels: Binary exact, hellfire

#2171 PrintItemPower
  Source/items.cpp
Labels: Binary exact, hellfire

#2170 [hellfire] CalcPlrItemVals
  Source/items.cpp
Labels: Minimal differences

#2176 [hellfire] SpawnBoy
  Source/items.cpp
  defs.h
Labels: Binary exact, hellfire

#2175 [hellfire] SpawnWitch
  Source/items.cpp
  defs.h
Labels: Binary exact, hellfire

#2179 [hellfire] WitchRechargeOk
  Source/stores.cpp
Labels: Minimal differences, hellfire

#2177 Clean up PrintSString
  Source/stores.cpp
Labels: Minimal differences, code cleanup, hellfire

#2178 [hellfire] WitchSellOk
  Source/stores.cpp
Labels: Minimal differences, hellfire

#2181 [hellfire] CheckPlrSpell bin exact
  Source/player.cpp
Labels: Binary exact, code cleanup, hellfire

#2183 mpqapi_new_block bin exact
  Source/mpqapi.cpp
Labels: Binary exact, code cleanup, hellfire

#2182 mpqapi_find_free_block bin exact
  Source/mpqapi.cpp
Labels: Binary exact, code cleanup, hellfire

#2184 mpqapi_get_hash_index bin exact
  Source/mpqapi.cpp
Labels: Binary exact, code cleanup, hellfire

#2189 [hellfire] MI_FirewallC
  Source/missiles.cpp
  defs.h
Labels: Binary exact, hellfire

#2187 Clean up missiles_steal_pots
  Source/missiles.cpp
Labels: Binary exact, code cleanup, hellfire

#2188 [hellfire] AddFirewall
  Source/missiles.cpp
Labels: Binary exact, hellfire

#2190 [hellfire] MI_Lightctrl and mi_light_arrow
  Source/missiles.cpp
Labels: Binary exact, hellfire

#2191 Clean up mpqapi_write_file_contents
  Source/mpqapi.cpp
Labels: Binary exact, code cleanup, hellfire

#2185 [hellfire] MonsterMHit
  Source/missiles.cpp
  structs.h
Labels: Binary exact, hellfire
