Repository diasurgical/devilution, pull requests merged in 2020-03, with the labels that each got.

#2002 Several updates [enums+names]
  Source/diablo.cpp
  Source/drlg_l1.cpp
  Source/drlg_l2.cpp
  Source/drlg_l3.cpp
  Source/drlg_l4.cpp
  Source/inv.cpp
  Source/items.cpp
  Source/monstdat.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/msg.h
  Source/multi.cpp
  Source/objects.cpp
  Source/player.cpp
  Source/quests.cpp
  Source/setmaps.cpp
  Source/stores.cpp
  Source/themes.cpp
  Source/town.cpp
  Source/towners.cpp
  Source/trigs.cpp
  comparer-config/diablo.toml
  comparer-config/spawn.toml
  enums.h
Labels: code cleanup

#1994 [hellfire] NetSendCmdMonDmg
  Source/msg.cpp
  Source/msg.h
  structs.h
Labels: Binary exact, hellfire

#1990 [hellfire] CheckMonsterHit
  Source/monster.cpp
Labels: Binary exact, hellfire

#1987 [hellfire] PostOkMonst, PostOkMonst2, PostOkMonst3 and monster_posok
  Source/monster.cpp
  Source/monster.h
Labels: Binary exact, Minimal differences, hellfire

#1974 Names and bug fixes
  Source/control.cpp
  Source/control.h
  Source/drlg_l1.cpp
  Source/drlg_l2.cpp
  Source/gendung.cpp
  Source/gendung.h
  Source/items.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/msg.h
  Source/multi.cpp
  Source/objects.cpp
  Source/player.cpp
  Source/scrollrt.cpp
  Source/town.cpp
Labels: code cleanup

#1961 Reorder globals
  Source/cursor.cpp
  Source/cursor.h
  Source/diablo.cpp
  Source/diablo.h
  Source/drlg_l2.cpp
  Source/drlg_l2.h
  Source/drlg_l4.cpp
  Source/drlg_l4.h
  Source/quests.cpp
  Source/quests.h
Labels: code cleanup

#1951 [hellfire] InitStores
  Source/stores.cpp
Labels: Binary exact, hellfire

#2021 Fix function/var names (effects/sound)
  Source/diablo.cpp
  Source/effects.cpp
  Source/effects.h
  Source/gamemenu.cpp
  Source/interfac.cpp
  Source/movie.cpp
  Source/player.cpp
  Source/sound.cpp
  Source/sound.h
  Source/stores.cpp
  Source/stores.h
  Source/towners.cpp
  comparer-config/diablo.toml
  comparer-config/spawn.toml
Labels: code cleanup

#2022 [hellfire] S_StartSIdentify bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2023 [hellfire] S_BBuyEnter bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2033 [hellfire] S_StartHealer bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2032 [hellfire] S_StartSSell bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2031 [hellfire] S_StartWSell bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2030 [hellfire] S_StartSRepair bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2029 [hellfire] S_StartWRecharge bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire

#2028 [hellfire] S_StartBBoy bin exact
  Source/stores.cpp
Labels: Binary exact, hellfire
