Repository diasurgical/devilution, pull requests merged in 2020-11, with the labels that each got.

#2145 some cleanups
  Source/diablo.cpp
  Source/objects.cpp
  enums.h
Labels: code cleanup

#2146 some cleanup
  Source/monster.cpp
  Source/objects.cpp
  Source/quests.cpp
  Source/themes.cpp
  enums.h
Labels: code cleanup

#2147 Bugfix
  Source/missiles.cpp
  Source/monster.cpp
  Source/objects.cpp
  enums.h
Labels: Binary exact, code cleanup

#2148 [hellfire] NetSendCmdGItem2 binexact
  Source/msg.cpp
Labels: Binary exact, hellfire

#2149 msg.cpp functions bin exact
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2150 2 functions
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2151 [Hellfire] DoEnding BinExact
  Source/monster.cpp
Labels: Binary exact, hellfire

#2124 WIP CheckInvPaste
  Source/inv.cpp
Labels: hellfire

#2152 monsters cleanup
  Source/cursor.cpp
  Source/missiles.cpp
  Source/monstdat.cpp
  Source/monstdat.h
  Source/monster.cpp
  enums.h
Labels: Binary exact, code cleanup, hellfire

#2154 msg.cpp cleanup
  Source/msg.cpp
Labels: Binary exact, code cleanup, hellfire

#2155 codefix message
  Source/sync.cpp
Labels: code cleanup

#2156 Cleanup11
  Source/msg.cpp
  Source/player.cpp
  Source/scrollrt.cpp
Labels: code cleanup

#2158 GetTempSaveNames/GetPermSaveNames
  Source/pfile.cpp
Labels: Binary exact, code cleanup, hellfire

#2159 SyncMonsterAnim bin exact
  Source/monster.cpp
Labels: Binary exact, code cleanup, hellfire

#2161 some cleanup
  Source/inv.cpp
  Source/items.cpp
  Source/objects.cpp
  Source/player.cpp
Labels: code cleanup
